### ISSUE TITLE
Agglomeration Crafting

### ISSUE THREAD

**Issue by FlashGamer12302** [DoremySwee/Art-of-Enigma#2]
I cannot add the pickaxe to the agglomeration plate for the one craft. It has full durability and I have even tried placing the items in different orders.

**Comment by DoremySwee** [comment]
> I cannot add the pickaxe to the agglomeration plate for the one craft. It has full durability and I have even tried placing the items in different orders.

Use [Q] to throw it onto the plate, instead of right clicking the plate with the item.
